### PR TITLE
add airdrop note

### PR DESCRIPTION
**Pull request by DougAnderson444**
add airdrop note

### CODE REVIEW

**Comment by DougAnderson444** [comment]
https://discord.com/channels/357957786904166400/817766991799648286/910819951047229470

**Comment by cedriking** [comment]
Hello @DougAnderson444 , this is not really accurate. Wallet addresses return a balance of 0 if you don't set any balance before. It is true that you can mint an unlimited amount, but it's not true that the balances are infinite.

Thanks for the PR!

**Comment by DougAnderson444** [comment]
Ok, can we add how to mint the unlimited amount then? I didn't see that
anywhere, although I haven't had any issues deploying a contract from a
random keypair

**Comment by cedriking** [comment]
Added the details on the readme. Also if you're using an older version it will work as expected. This was a WIP and changes started to appear this week :)

**Pull request closed without merging**
